/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.DtPromocion;
import Logica.DtServicio;
import Logica.DtUsuario;
import Logica.Fabrica;
import Logica.IControladorServicio;
import Logica.ManejadorProveedor;
import java.util.Iterator;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hekutoru
 */
public class AltaPromocion extends javax.swing.JInternalFrame {

    private IControladorServicio IControlador;
    private DefaultTableModel modelo;
    private List<DtServicio> listaServicios;
    private List<DtUsuario> listaProveedores;

    private String[] columnas = {"Cantidad", "Nombre", "Proveedor", "Precio"};
    private DefaultTableCellRenderer centerRenderer;
    private DefaultTableCellRenderer rightRenderer;

    /**
     * Creates new form AltaPromocion
     */
    public AltaPromocion() {
        initComponents();

        cargarProveedores();

        Fabrica fabrica = Fabrica.getInstance();
        this.IControlador = fabrica.getIControladorServicio();

        jTextFieldTotal.setHorizontalAlignment(SwingConstants.RIGHT);
        jTextFieldDesc.setHorizontalAlignment(SwingConstants.RIGHT);
        jTextFieldFinal.setHorizontalAlignment(SwingConstants.RIGHT);

        listaServicios = this.IControlador.listarServicios();
        Iterator<DtServicio> i = listaServicios.iterator();

        this.modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0;
            }
        };

        while (i.hasNext()) {
            DtServicio serv = i.next();
            Object[] fila = {
                0,
                serv.getNombre(),
                serv.getNkProveedor(),
                serv.getPrecio()};
            modelo.addRow(fila);
        }
        jTableOfertas.setModel(modelo);
        modelo.addTableModelListener(jTableOfertas);

        this.centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        this.rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        jTableOfertas.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTableOfertas.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
    }

    public void celdaEditada(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        DefaultTableModel model = (DefaultTableModel) e.getSource();
        String columna = model.getColumnName(column);
        Object data = model.getValueAt(row, column);
        calcularTotal();
    }

    public void calcularTotal() {
        Double subtotal = 0.0;
        int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            Integer cantidad = Integer.valueOf(modelo.getValueAt(i, 0).toString());
            Float precio = Float.valueOf(modelo.getValueAt(i, 3).toString());
            subtotal += cantidad * precio;
        }
        jTextFieldTotal.setText(subtotal.toString());
        Integer porcentaje = Integer.valueOf(jSpinnerPor100.getValue().toString());
        Double descuento = subtotal * porcentaje / 100;
        jTextFieldDesc.setText(descuento.toString());
        Double total = subtotal - descuento;
        jTextFieldFinal.setText(total.toString());
    }

    public DtPromocion armarDtPromo() {
        DtPromocion dtp = new DtPromocion(
                jTextFieldPromo.getText(),
                jComboBoxProv.getSelectedItem().toString(),
                jTextFieldDesc.getText(),
                jTextFieldFinal.getText());
        System.out.println(dtp);
        return dtp;
    }

    private void cargarProveedores() {
        jComboBoxProv.removeAllItems();
        this.listaProveedores = ManejadorProveedor.getInstance().listarProveedores();
        Iterator<DtUsuario> iter = listaProveedores.iterator();
        while (iter.hasNext()) {
            String proveedor = iter.next().getNickname();
            this.jComboBoxProv.addItem(proveedor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPromo = new javax.swing.JLabel();
        jTextFieldPromo = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOfertas = new javax.swing.JTable();
        jLabelServ = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jLabelTotal1 = new javax.swing.JLabel();
        jTextFieldFinal = new javax.swing.JTextField();
        jLabelTotal2 = new javax.swing.JLabel();
        jSpinnerPor100 = new javax.swing.JSpinner();
        jComboBoxProv = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPromo1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Promoción");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-icon.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 300));

        jLabelPromo.setText("[1] Ingrese el nombre de la nueva promoción:");

        jTextFieldPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPromoActionPerformed(evt);
            }
        });
        jTextFieldPromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPromoKeyReleased(evt);
            }
        });

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/check-icon.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.setFocusable(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel-icon.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setFocusable(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Nombre", "Proveedor", "Precio"
            }
        ));
        jTableOfertas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableOfertasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOfertas);

        jLabelServ.setText("[4] Ingrese en la primera columna la cantidad de cada uno de los servicios asociados a la promoción:");

        jLabelTotal.setText("Precio total ($):");
        jLabelTotal.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh-icon.png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setText("0.0");

        jLabelDesc.setText("[3] Ingrese el descuento aplicado (%):");

        jTextFieldDesc.setEditable(false);
        jTextFieldDesc.setText("0.0");

        jLabelTotal1.setText("Descuento total ($):");
        jLabelTotal1.setEnabled(false);

        jTextFieldFinal.setEditable(false);
        jTextFieldFinal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextFieldFinal.setText("0.0");

        jLabelTotal2.setText("Precio final ($):");
        jLabelTotal2.setEnabled(false);

        jSpinnerPor100.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerPor100StateChanged(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Proveedor:");

        jLabel3.setText("Descuento:");

        jLabelPromo1.setText("[2] Seleccione el proveedor de la promoción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotal)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDesc)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTotal2)
                            .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelServ)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelPromo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPromo)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPromo1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPor100, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPromo)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPromo1)
                    .addComponent(jLabelDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerPor100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTotal1)
                    .addComponent(jLabelTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTextFieldTotal.setHorizontalAlignment(SwingConstants.RIGHT);
        jTextFieldTotal.setHorizontalAlignment(SwingConstants.RIGHT);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPromoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        IControlador.altaDePromocion(armarDtPromo());
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldPromoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPromoKeyReleased
        if (jTextFieldPromo.getText().isEmpty()) {
            jButtonAceptar.setEnabled(false);
        } else {
            jButtonAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldPromoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularTotal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinnerPor100StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerPor100StateChanged
        calcularTotal();
    }//GEN-LAST:event_jSpinnerPor100StateChanged

    private void jTableOfertasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOfertasKeyReleased
        calcularTotal();
    }//GEN-LAST:event_jTableOfertasKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelPromo;
    private javax.swing.JLabel jLabelPromo1;
    private javax.swing.JLabel jLabelServ;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotal1;
    private javax.swing.JLabel jLabelTotal2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPor100;
    private javax.swing.JTable jTableOfertas;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldFinal;
    private javax.swing.JTextField jTextFieldPromo;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
