/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Fabrica;
import Logica.IControladorServicio;
import Logica.ManejadorCategoria;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP Usuario
 */
public class AltaCategoria2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form altaCategoria
     */
    List<String> listaCategorias;
    private IControladorServicio IControlador;

    public AltaCategoria2() {
        initComponents();

        Fabrica fabrica = Fabrica.getInstance();
        this.IControlador = fabrica.getIControladorServicio();
        this.listaCategorias = ManejadorCategoria.getInstance().getNombresCategorias();
        Iterator<String> iter = this.listaCategorias.iterator();
        while (iter.hasNext()) {
            String nomCat = iter.next();
            this.jComboBoxPadre.addItem(nomCat);
        }
        //jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCateg = new javax.swing.JLabel();
        jTextFieldCateg = new javax.swing.JTextField();
        jLabelPadre = new javax.swing.JLabel();
        jCheckBoxPadre = new javax.swing.JCheckBox();
        jComboBoxPadre = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alta Categoria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-icon.png"))); // NOI18N

        jLabelCateg.setText("Ingrese el nombre de la nueva categoría:");

        jTextFieldCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategActionPerformed(evt);
            }
        });
        jTextFieldCateg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCategKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCategKeyTyped(evt);
            }
        });

        jLabelPadre.setText("Si la categoría tiene padre, ingréselo aqui:");

        jCheckBoxPadre.setText("Padre");
        jCheckBoxPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPadreActionPerformed(evt);
            }
        });

        jComboBoxPadre.setEnabled(false);
        jComboBoxPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPadreActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel-icon.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/check-icon.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setActionCommand("aceptar");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCateg)
                    .addComponent(jLabelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxPadre)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPadre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCateg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelCateg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPadre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPadre)
                    .addComponent(jComboBoxPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategActionPerformed
        this.jTextFieldCateg.setText("");
    }//GEN-LAST:event_jTextFieldCategActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String respuesta;
        if (this.jCheckBoxPadre.isSelected()) {
            respuesta = IControlador.altaDeCategoria(jTextFieldCateg.getText(), jComboBoxPadre.getSelectedItem().toString());
        } else {
            respuesta = IControlador.altaDeCategoria(jTextFieldCateg.getText(), null);
        }
        JOptionPane.showMessageDialog(null, respuesta);
        this.dispose();

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jCheckBoxPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPadreActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxPadre.isSelected()) {
            jComboBoxPadre.setEnabled(true);
        } else {
            jComboBoxPadre.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxPadreActionPerformed

    private void jComboBoxPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPadreActionPerformed

    private void jTextFieldCategKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCategKeyTyped

    }//GEN-LAST:event_jTextFieldCategKeyTyped

    private void jTextFieldCategKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCategKeyReleased
        if (jTextFieldCateg.getText().isEmpty()) {
            jButtonAceptar.setEnabled(false);
        } else {
            jButtonAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldCategKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxPadre;
    private javax.swing.JComboBox<String> jComboBoxPadre;
    private javax.swing.JLabel jLabelCateg;
    private javax.swing.JLabel jLabelPadre;
    private javax.swing.JTextField jTextFieldCateg;
    // End of variables declaration//GEN-END:variables
}
