/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Date;
import Logica.DtUsuario;
import Logica.Fabrica;
import Logica.IControladorReserva;
import Logica.IControladorUsuario;
import Logica.Proveedor;
import Logica.Reserva;
import Logica.Servicio;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;

public class altaReserva extends javax.swing.JInternalFrame {

    private IControladorUsuario IControlador;
    private IControladorReserva IReservas;
    private ArrayList<DtUsuario> listaClientes;
    private static DefaultTableModel modelo;

    public altaReserva() {
        initComponents();

        //Obtengo interfaces
        Fabrica fabrica = Fabrica.getInstance();
        this.IControlador = fabrica.getIControladorUsuario();
        this.IReservas = fabrica.getIControladorReserva();

        //Agregar los usuarios al combo box
        this.listaClientes = this.IControlador.listarClientes();
        Iterator<DtUsuario> i = this.listaClientes.iterator();
        while (i.hasNext()) {
            DtUsuario user = i.next();
            this.clientes.addItem(user.getNickname());
        }

        //Setear tabla
        modelo = (DefaultTableModel) items.getModel();
        modelo.setRowCount(0);

        //Seteo otros
        total.setText("");
        if (!listaClientes.isEmpty()) {
            clientes.setSelectedIndex(1);
        }
        total.setText("0");
        sumaPrecios.setText("0");
    }

    public static void agregarItem(Object[] item, double dTotal) {
        modelo.addRow(item);
        sumaPrecios.setText(String.valueOf(Double.parseDouble(sumaPrecios.getText()) + (dTotal)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        items = new javax.swing.JTable();
        crear = new javax.swing.JButton();
        sumaPrecios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nueva reserva");

        jLabel1.setText("Usuario:");

        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio final:");

        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-icon.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete-icon.png"))); // NOI18N
        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Cantidad", "Item", "Proveedor", "Inicio", "Fin", "Precio p/u", "Precio total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(items);
        if (items.getColumnModel().getColumnCount() > 0) {
            items.getColumnModel().getColumn(0).setMinWidth(40);
            items.getColumnModel().getColumn(0).setMaxWidth(40);
            items.getColumnModel().getColumn(1).setMinWidth(70);
            items.getColumnModel().getColumn(1).setMaxWidth(70);
            items.getColumnModel().getColumn(4).setMinWidth(100);
            items.getColumnModel().getColumn(4).setMaxWidth(100);
            items.getColumnModel().getColumn(5).setMinWidth(100);
            items.getColumnModel().getColumn(5).setMaxWidth(100);
            items.getColumnModel().getColumn(6).setMinWidth(100);
            items.getColumnModel().getColumn(6).setMaxWidth(100);
            items.getColumnModel().getColumn(7).setMinWidth(100);
            items.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/check-icon.png"))); // NOI18N
        crear.setText("Crear");
        crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearMouseClicked(evt);
            }
        });
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        sumaPrecios.setEditable(false);
        sumaPrecios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sumaPreciosKeyTyped(evt);
            }
        });

        jLabel3.setText("Precio total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sumaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(sumaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crear)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped

    }//GEN-LAST:event_totalKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        altaReserva2 listaOfertas = new altaReserva2();
        Principal.escritorio.add(listaOfertas);
        Dimension desktopSize = Principal.escritorio.getSize();
        Dimension FrameSize = listaOfertas.getSize();
        listaOfertas.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        listaOfertas.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (!Boolean.valueOf(String.valueOf(modelo.getValueAt(i, 0)))) {
                
                //Resto el valor del item del total.
                double dItem = Double.parseDouble(String.valueOf(modelo.getValueAt(i, 7)));
                double dTotal = Double.parseDouble(sumaPrecios.getText());
                sumaPrecios.setText(String.valueOf(dTotal - dItem));
                
                //Elimino item
                modelo.removeRow(i);
                i += -1;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseClicked

        Reserva nReserva = IReservas.nuevaRserva(String.valueOf(clientes.getSelectedItem()), Double.parseDouble(total.getText()));

        for (int i = 0; i < modelo.getRowCount(); i++) {
            int cantidad = Integer.parseInt(String.valueOf(modelo.getValueAt(i, 1)));
            int dia, mes, ano;

            //Fecha inicio
            StringTokenizer in = new StringTokenizer(String.valueOf(modelo.getValueAt(i, 4)), "-", false);
            ano = Integer.parseInt(in.nextToken());
            mes = Integer.parseInt(in.nextToken());
            dia = Integer.parseInt(in.nextToken());
            Date inicio = new Date(dia, mes, ano);

            //Fecha fin
            StringTokenizer fi = new StringTokenizer(String.valueOf(modelo.getValueAt(i, 5)), "-", false);
            ano = Integer.parseInt(fi.nextToken());
            mes = Integer.parseInt(fi.nextToken());
            dia = Integer.parseInt(fi.nextToken());
            Date fin = new Date(dia, mes, ano);
            String servicio = String.valueOf(modelo.getValueAt(i, 2));
            String proveedor = String.valueOf(modelo.getValueAt(i, 3));

            IReservas.agregarItem(nReserva, cantidad, inicio, fin, new Servicio(servicio, new Proveedor(proveedor)));
        }

        nReserva.setEstado(Reserva.eEstado.REGISTRADA);
        java.util.Date actual = new java.util.Date();
        String fecha, dia, mes, ano;
        dia = String.valueOf(actual.getDay());
        mes = String.valueOf(actual.getMonth());
        ano = String.valueOf(actual.getYear() - 100);

        System.out.println(ano);

        ano = "20" + ano;
        if (mes.length() == 1) {
            mes = "0" + mes;
        }
        if (dia.length() == 1) {
            dia = "0" + dia;
        }

        nReserva.setCreada(new Date(Integer.parseInt(dia), Integer.parseInt(mes), Integer.parseInt(ano)));
        IReservas.altaReserva(nReserva);
        this.dispose();
    }//GEN-LAST:event_crearMouseClicked

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    private void sumaPreciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumaPreciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaPreciosKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clientes;
    private javax.swing.JButton crear;
    private javax.swing.JTable items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextField sumaPrecios;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
