/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Cliente;
import Logica.DtReserva;
import Logica.DtUsuario;
import Logica.Fabrica;
import Logica.IControladorUsuario;
import static Logica.Reserva.eEstado.REGISTRADA;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yaman
 */
public class verInfoCliente extends javax.swing.JInternalFrame {

    private IControladorUsuario IControlador;
    private ArrayList<DtUsuario> listaClientes;
    private DefaultTableModel modeloTablaRs;
    private DefaultTableModel modeloTablaCl;

    /**
     * Creates new form verInfoCliente
     */
    public verInfoCliente() {
        initComponents();

        Fabrica fabrica = Fabrica.getInstance();
        this.IControlador = fabrica.getIControladorUsuario();

        DefaultListModel modelo = new DefaultListModel();
        
        this.listaClientes = this.IControlador.listarClientes();
        Iterator<DtUsuario> i = this.listaClientes.iterator();
        while (i.hasNext()) {
            DtUsuario user = i.next();
            modelo.addElement(user.getNombre());
        }

        jListaClientes.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaClientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaReservas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jListaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListaClientes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("CLIENTES");

        jTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nickname", "nombre", "apellido", "nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablaClientes);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DATOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("RESERVAS");

        jTablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "estado", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablaReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaClientesMouseClicked

        String nombre = jListaClientes.getSelectedValue();

        String[] columnasClientes = {"nickname", "nombre", "apellido", "nacimiento"};

        String[] registrosClientes = new String[4];

        String[] columnasReservas = {"id", "estado", "total"};

        String[] registrosReservas = new String[3];

        modeloTablaCl = new DefaultTableModel(null, columnasClientes);
        modeloTablaRs = new DefaultTableModel(null, columnasReservas);

        Iterator<DtUsuario> i = this.listaClientes.iterator();
        boolean es = false;
        while (i.hasNext() & !es) {
            DtUsuario user = i.next();
            if (nombre.equals(user.getNombre())) {
                es = true;

                registrosClientes[0] = user.getNombre();
                registrosClientes[1] = user.getApellido();
                registrosClientes[2] = user.getNickname();
                registrosClientes[3] = user.getNacimiento().getFecha("-");

                modeloTablaCl.addRow(registrosClientes);
                jTablaClientes.setModel(modeloTablaCl);

                Fabrica fabrica = Fabrica.getInstance();

                ArrayList<DtReserva> listaReservas = fabrica.getIControladorUsuario().listarReservasCliente(user);

                Iterator<DtReserva> iter = listaReservas.iterator();
                modeloTablaRs.setRowCount(0);
                DtReserva res;
                while (iter.hasNext()) {
                    res = iter.next();
                    registrosReservas[0] = Integer.toString((int) res.getId());
                    String estado="";
                    switch (res.getEstado()) {
                    case REGISTRADA: estado = "REGISTRADA";
                     break;
                    case CANCELADA:  estado = "CANCELADA";
                     break;
                    case FACTURADA:  estado = "FACTURADA";
                     break;
                    case PAGADA:  estado = "PAGADA";
                     break;
                    }
                             
                    
                    registrosReservas[1] = estado;
                    registrosReservas[2] = Double.toString(res.getTotal());

                    modeloTablaRs.addRow(registrosReservas);

                }
            }
            jTablaReservas.setModel(modeloTablaRs);

    }//GEN-LAST:event_jListaClientesMouseClicked
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListaClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablaClientes;
    private javax.swing.JTable jTablaReservas;
    // End of variables declaration//GEN-END:variables
}
